version: 2.1
jobs:
  build:
    docker:
    - image: node:11.15.0-alpine
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: yarn
    - run:
        name: Build
        command: yarn build
